### ISSUE TITLE
The test tests/test_jailbreak.py::TestJailbreak::test_mul_overflow runs in  a very high memory - 12+GB

### ISSUE THREAD

**Issue by yurivict** [yaroslaff/evalidate#8] opened 2023-07-10 02:09 UTC
Version: 2.0.2
Python-3.9
FreeBSD 13.2

**Comment by yaroslaff** [comment] 2023-07-11 08:55
Does it passes test for you?
(it must raise `ExecutionException` and test code expects for this exception. Test is successful if exception raised finally)

`Mult` operation is dangerous especially for this reason: malicious user could consume too much RAM, so we have two options:
1. Catch this problem with ExecutionException (test checks for this)
2. Prevent this problem, not allowing `Mult` operation (when it's possible).

For me (on Linux) test runs very quickly, so I do not even see how much memory it allocates during this very short-test (maybe it allocates some memory, but then got exception and releases it). For you, this allocation and test runs lasts for long time? What does `time pytest tests/test_jailbreak.py` says? (0.37s for me)

**Comment by yaroslaff** [comment] 2023-10-15 11:47
Closing, because problem is only in test and I cannot reproduce it on linux and not getting feedback

**Closed** 2023-10-15 11:47 UTC
